### ISSUE TITLE
Horizontal scrollbar on 1280px

### ISSUE THREAD

**Issue by vitalyster** [vlang/website#67]

**Comment by SlipperyDuck777** [comment]
Sorry I do not understand. Can you please provide me with more information so I can attempt to fix whatever issue this is?
Are you referencing that a scrollbar appears? Which it does on many computer due to browser default settings. But it could be removed with this:
```css
body {
  overflow: hidden;
}
```
Or if you just want to make sure no horizontal scrollbar ever shows up on any screen you could do this:
```css
body {
  overflow-x: hidden;
}
```
Either way I would keep the vertical scrollbar and use the second option although I am not sure what the issue is as not enough information is provided.
